### ISSUE TITLE
Add implementation for Batch emit usage

### ISSUE THREAD

**Issue by ankisho** [Azure/Microsoft-commercial-marketplace-transactable-SaaS-offer-SDK#28] opened 2020-04-14 14:09 UTC
**Is your feature request related to a problem? Please describe.**
A Yes, Batch emit usage is mostly used feature and it's not implemented. Partners have to implement For loop to achieve batch emit usage.

**Describe the solution you'd like**
A Implement batch emit usage feature.

**Describe alternatives you've considered**
A No..

**Additional context**

**Comment by dev-kiranbanda** [comment] 2020-06-17 07:36
@code4clouds  - I think we can close this one as this is a duplicate of Issue #34

**Comment by ankisho** [comment] 2020-06-17 08:23
@dev-kiranbanda : yes. lets close the #34 . this is feature request was opened earlier. Just to keep track. We can enhancement label here.

**Comment by code4clouds** [comment] 2020-06-17 15:30
Closing as this is now addressed on #34

**Closed by code4clouds** 2020-06-17 15:30 UTC
